yahoojapan/authorization-proxy

README.md
config/config.go
config/config_test.go
config/testdata/example_config.yaml
go.sum
k8s/gen.sh
main_test.go
service/doc.go
usecase/providerd.go
usecase/providerd_test.go

Signed-off-by: kpango <i.can.feel.gravity@gmail.com>

[minor] update athenz-policy-updator

---

doc/graceful-shutdown.md
k8s/gen.sh
service/server.go

[patch] change default value of ShutdownDuration and ProbeWaitTime

---

service/server_test.go

add test case "Test other servers stop when debug server stops"

---

go.mod
go.sum

Fix check policy logic as denied policy will be prioritized.

[patch] update dependencies version

---

.circleci/config.yml

[patch] fix release failed

---

.circleci/config.yml

similar PR: https://github.com/yahoojapan/athenz-client-sidecar/pull/29

[patch] version is not added on released steps

---

.circleci/config.yml
go.mod
handler/handler.go
handler/handler_test.go
handler/transport.go
handler/transport_test.go
main.go
main_test.go
router/debug_router.go
router/debug_router_test.go
router/debug_routes.go
router/debug_routes_test.go
service/option.go
service/option_test.go
service/server.go
service/server_test.go
service/tls.go
service/tls_test.go
usecase/authz_proxyd.go
usecase/authz_proxyd_test.go

[patch] update version to v2

---

usecase/authz_proxyd.go

[skip ci] RT back compatibility, always set RT header

---

.circleci/config.yml

[patch] Add v prefix

---

.circleci/config.yml

[patch] RT back compatibility, Add`v` prefix in pipeline

---

config/config.go
config/config_test.go
config/testdata/example_config.yaml
config/testdata/undefine_roletoken.yaml
main_test.go
usecase/authz_proxyd.go
usecase/authz_proxyd_test.go

Added an option to force roletoken to be enable.

[patch] Add roletoken option and force enable

---

config/config.go

Added an explanation for forced enable of roletoken.

[skip] Add explanation that roletoken is force true

---

config/config.go
go.mod
go.sum
test/data/example_config.yaml
usecase/authz_proxyd.go
usecase/authz_proxyd_test.go

_description_with_details_and_reasoning_
**Delete if not applicable**
- Fixes #_issue_
- Closes #_PR_
---

[patch] Add policy disable

---

go.mod
go.sum

_description_with_details_and_reasoning_
**Delete if not applicable**
- https://github.com/yahoojapan/athenz-authorizer/pull/76
---

[patch] Update version

---

docs/debug.md
go.mod
go.sum

This is a PR to import fixes for bugs related to regular expressions.
TODO:
- https://github.com/yahoojapan/athenz-authorizer/pull/73
- PR purpose is to import this PR modification.
- https://github.com/yahoojapan/athenz-authorizer/pull/73
---

[minor] Fix regex bug

---

go.mod
handler/handler.go
handler/handler_test.go
handler/transport.go
handler/transport_test.go
main.go
main_test.go
router/debug_router.go
router/debug_router_test.go
router/debug_routes.go
router/debug_routes_test.go
service/option.go
service/option_test.go
service/server.go
service/server_test.go
service/tls.go
service/tls_test.go
usecase/authz_proxyd.go
usecase/authz_proxyd_test.go

[patch] Fix go.mod major version

---

handler/handler.go

BadGateway時のログを `Debug` から `Warn` に変更します。
---

[skip] Modify Badgateway log level

---

.circleci/config.yml

change docker hub user and split docker hub repo name in pipeline
---

[skip] change docker user in pipeline

---

handler/handler_test.go
service/tls_test.go

[patch] fix lint for unit test

---

handler/handler.go
handler/handler_test.go
service/server.go
service/server_mock.go
service/server_test.go

This fix will prevent some crashes.
---

[patch] fix: avoid crush

---

config/config.go

add omitempty for golang transport config
---

[patch] add omitempty for golang transport config

---

CONTRIBUTING.md
README.md

[patch] release

---

Dockerfile

_description_with_details_and_reasoning_
**Delete if not applicable**
- Fixes #_issue_
- Closes #_PR_
---

[patch] Update Dockerfile to restore USER
